# Generated by Django 4.0.4 on 2022-05-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0002_remove_sheet_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='delivery_time',
            field=models.CharField(max_length=10),
        ),
    ]
