# Generated by Django 4.0.4 on 2022-05-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0003_alter_sheet_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='order',
            field=models.IntegerField(max_length=7),
        ),
    ]
