# Generated by Django 4.0.4 on 2022-05-20 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0004_alter_sheet_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheet',
            old_name='order',
            new_name='order_number',
        ),
    ]
