# Generated by Django 4.0.4 on 2022-05-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0006_alter_sheet_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='delivery_time',
            field=models.CharField(max_length=10),
        ),
    ]
