# Generated by Django 4.0.4 on 2022-05-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0007_alter_sheet_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='number',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
