# Generated by Django 4.0.4 on 2022-05-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0008_sheet_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='order_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='price_rur',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='price_usd',
            field=models.CharField(max_length=10),
        ),
    ]
